language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
after_success:
- "./gradlew bintrayUpload artifactoryPublish"
env:
  global:
  - bintrayUser=kruton
  - secure: JFI32ls/WOlpgYd+R+SqQeI27ECLmSh3tonjwOevu9Shnh3pUnihwxFsab7jYTV2qEzj89xaSBZwiZNswtmyyDB1yOVEUlKBgnhtQwNG31PbG9KZsHO8SpcVWUuw/bMMLml7mbpfIoTPQYJjLEidmkRxP/UVkUrAcRaq2wRx6LxtIhX2eX7PF51Nob4PNVO5vUXUveEDYHwKtRBbo35FcV8nT9cnP7r3gVWIlVLhCi93XPBLoFoJ0bbR/Ynrw2KnM0MEqlZF5CXRH7Kwx/A+qWkgnQUsDmMDxnEW6aIE7VqX9j8IsSHcpnI8e2dq8NckZ5ECAW3QVdnwjzI2yd+DKxEMaPN/BqQT9he/PNVo+jz14C/knUAuNFd0exu8Nw8KIi2McdsdqeQno3thGk5x3dr3AJ9J03Oz7FS7HKhYCASpnOi3QNWYEr9rt+9u4od/9fiRAKlwoTGWw7AyicriFwjzs7yIvPW2AE1Usd5VZW/YKZiyK4vxVMtjxFagA+mCU2VxSEUlBdPve9Gt2n5nUOapFlkvt5pFuapVNOjtj+bb8Wnr2rAOEiD6ttIsH3T/gQwnukDc3pDNI/SR5/pkddOgBgRevRN6eewkwIZwaWCdfyVeHR2Ob4sl6d2eVIbb/NN6LLYZwgpnO8T0JiRsofY2uaGKi8YxxquodUVkSF0=
